title: Data visualization with Python
description: Makes you want to never use MS Office charts ever again.
theme: just-the-docs
color_scheme: foo

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
