title: Data visualization with Python
description: Makes you want to never use MS Office charts ever again.
theme: just-the-docs
color_scheme: foo

aux_links_new_tab: true
heading_anchors: true

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
